### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by mdeceglie** [slacgismo/solar-data-tools#105]
Adding docstrings to the functions, classes, and methods would help users navigate the capabilities. Consider using [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) style to facilitate integration with sphinx.

**Comment by pluflou** [comment]
Late to the conversation here, but we are working on a revamp of our docs in [this branch](https://github.com/slacgismo/solar-data-tools/tree/documentation-sphinx), including NumPy style docstring and a complete list of API references in our [website](https://solar-data-tools.readthedocs.io/). So I am closing this issue for now. Thanks!
