### ISSUE TITLE
windows installation instructions are incomplete and/or packaging specs are incomplete

### ISSUE THREAD

**Issue by wholmgren** [slacgismo/solar-data-tools#139]
Hi folks. We're running into installation difficulties following the [recommend procedure](https://solar-data-tools.readthedocs.io/en/documentation-sphinx/install.html#set-up-conda-environment-with-provided-yml-file-recommended) using the yml file. Here's what we did:

```
> git clone solar-data-tools
> cd solar-data-tools
> git rev-parse --short HEAD
abc0dba
> conda env create -f pvi-user.yml
# wait an hour :(
```

Then try to run the [demo](https://solar-data-tools.readthedocs.io/en/documentation-sphinx/notebooks/demo_default.html). 

First issue I run into with the `solardatatools` import is that `qdldl` dll isn't loaded. I notice that `conda list` shows `qdldl` version of 0.1.7, but 0.1.7-post1 was just released. `pip install qdldl -U` solves the import problem.

Next issue is `tqdm` isn't installed. `pip install tqdm`. 

Run into another import issue: `No module named 'spcqe'`

Thinking: "this is weird... surely their packaging is not that incomplete." I see there's also a requirements.txt file in the repository. Installation instructions don't mention it but let's give it a shot. `pip install -r requirements.txt`. 

Now I can import the package and run the pipeline - hurray! 

Recommended solution: improve the yml specification and/or the package recipe so that all packages are available with recommended conda install path.

Alternative solution: add `pip install -r requirements.txt` to the installation instructions.

Incidental: pip complains about package incompatibilities:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
statistical-clear-sky 0.4.6 requires numpy==1.22.0, but you have numpy 1.26.0 which is incompatible.
```

Context: I watched the great Sandia/NREL/SLAC webinar a few weeks ago and thought it would be worth trying solar data tools on an upcoming project for a client. My colleague @amylynpierce ran into trouble following the installation instructions and I came in to troubleshoot.

**Comment by bt-** [comment]
I'm running into some of the same issues using the `pvi-user.yml` file to create a conda env. I'm on Linux and donwloaded the `pvi-user.yml` raw file rather than cloning initially.

It looks like qdldl did install for me. `conda list | grep qdldl` gives me:

> libqdldl                  0.1.7                h6a678d5_0    anaconda
> qdldl-python              0.1.7           py310h1128e8f_0    anaconda

So, the first issue I had was the tqdm import error. I deleted the conda environment, added tqdm to the yml file, created a new conda env with the modified yml.

Then, I hit the same spcqe import error.  After adding `spcqe` to the yml file I was able to create a conda env that would run the [General Usage](https://solar-data-tools.readthedocs.io/en/documentation-sphinx/usage.html) test without any import errors.

I opened pull request (#143) with the modified `pvi-user.yml`.

@wholmgren, are you using the conda solver or mamba solver? I'm using the mamba solver and it took only a few minutes.

**Comment by pluflou** [comment]
Hi @wholmgren and @bt- , sorry for the late response. I have a [PR](https://github.com/slacgismo/solar-data-tools/pull/140) that provides an update to all of the above (and we are actually deprecating the conda yaml file, instead we will recommend create a conda environment using `conda create -n pvi-user-conda slacgismo::solar-data-tools` from now on). I will ping you both here after that merge. Thank you for your patience!

**Comment by bt-** [comment]
@pluflou, no problem, sounds good. I saw that PR and wondered if possibly it might address this. Would you like me to close / remove the PR I created?

**Comment by pluflou** [comment]
@bt- we merged that PR yesterday, the conda release should be up to date now but we are still fixing a bug in the PyPI release--should be finalized within a day or two. I was planning to respond and close your PR once that's done, but if you want to close it now that works too. Thank you for contributing! Please let me know if you still have problems with the conda install (and thank you for your patience on the PyPI release). I'll wait to confirm that both work before closing this issue.

**Comment by pluflou** [comment]
Thank you for bringing this to our attention! We have now released an updated package version and new recommendations for [installation in the README](https://github.com/slacgismo/solar-data-tools/blob/main/README.md#install--setup). I am closing this issue, but please let us know if you run into other issues with the installation.
