### ISSUE TITLE
When plotting the polar transform we should be clipping the transformed data to be nonnegative.

### ISSUE THREAD

**Issue by bmeyers** [slacgismo/solar-data-tools#151]
https://github.com/slacgismo/solar-data-tools/blob/abc0dba44644cffc4fc8d9f9cbda306d61260dbf/solardatatools/polar_transform.py#L112C9-L112C42

clip as follows:

```
np.clip(self.transformed_data, 0, np.inf)
```

**Comment by pluflou** [comment]
Resolved in PR#52
