### ISSUE TITLE
Plotting of extra_matrices

### ISSUE THREAD

**Issue by toddkarin** [slacgismo/solar-data-tools#24]
It would be great if the plot_heatmap function in DataHandler could make it easy to plot the extra matrices. Should be just some simple modifications.

Also, currently plotting.plot_2d has a default title of "Measured Power", but this could easily be made into an input.

**Comment by toddkarin** [comment]
Additionally, the plot_heatmap function should include modifications so that if an irradiance sensor is analyzed, we can specify units of W/m2.

**Comment by bmeyers** [comment]
Very reasonable! Keep an eye out for the next release.

**Comment by bmeyers** [comment]
Done! in PR #38
