### ISSUE TITLE
Running with ECOS solver

### ISSUE THREAD

**Issue by toddkarin** [slacgismo/solar-data-tools#88]
I got the following error when trying to run the pipeline without a mosek license. The readme says that the solver uses ECOS as default, but this doesn't seem to be the case. Can you test again and provide instruction in the readme for switching between solvers?

<img width="896" alt="image" src="https://user-images.githubusercontent.com/18688594/200594999-c91e6dfb-8ce9-4222-b8c6-02d51c7d606a.png">

**Comment by bmeyers** [comment]
SDT only supports MOSEK at this time, as the readme states. We will be releasing v1 in a couple months that will remove MOSEK dependence.
